# Generated by Django 5.0 on 2023-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_project_ticket_ticketattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                related_name="assigned_users", to="accounts.project"
            ),
        ),
    ]
