# Generated by Django 5.0 on 2023-12-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketattachment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="accounts.ticket",
            ),
        ),
    ]
