# Generated by Django 5.0 on 2023-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_project_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
